<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Import inertial macros -->
    <xacro:include filename="inertial_macros.xacro"/>


    <!-- Physical Parameters -->
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.05"/>
    <xacro:property name="castor_radius" value="${wheel_radius/2}"/>
    <xacro:property name="chassis_y_len" value="0.3"/>
    <xacro:property name="chassis_x_len" value="0.3"/>
    <xacro:property name="chassis_z_len" value="0.15"/>

    <xacro:property name="wheel_mass" value="0.1"/>
    <xacro:property name="chassis_mass" value="0.5"/>
    <xacro:property name="castor_mass" value="0.1"/>

    <!-- Castor offset from chassis link -->
    <xacro:property name="castor_x" value="${chassis_x_len - chassis_x_len/7}"/>
    <xacro:property name="castor_y" value="0"/>
    <xacro:property name="castor_z" value="-${castor_radius}"/>

    <!-- Chassis offset from base link -->
    <xacro:property name="chassis_x" value="-0.1"/>
    <xacro:property name="chassis_y" value="0"/>
    <xacro:property name="chassis_z" value="0"/>

    <!-- Colors  -->

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name="blue">
        <color rgba="0 0 1 0.7"/>
    </material>

    <!-- Base Link  -->

    <link name="base_link">

    </link>

    <!-- Chassis Joint  -->

    <joint name="chassis_joint" type="fixed">
        <origin xyz="${chassis_x} ${chassis_y} ${chassis_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="chassis"/>
    </joint>

    <!-- Chassis Link  -->

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_x_len/2} 0 ${chassis_z_len/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_x_len} ${chassis_y_len} ${chassis_z_len}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${chassis_x_len/2} 0 ${chassis_z_len/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_x_len} ${chassis_y_len} ${chassis_z_len}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_x_len}" y="${chassis_y_len}" z="${chassis_z_len}">
            <origin xyz="${chassis_x_len/2} 0 ${chassis_z_len/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Left Wheel Joint  -->

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 ${chassis_y_len/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Left Wheel Link  -->

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Right Wheel Joint  -->

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 -${chassis_y_len/2 + wheel_width/2} 0" rpy="${pi/2} 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <!-- Right Wheel Link  -->

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Castor Joint  -->

    <joint name="castor_joint" type="fixed">
        <origin xyz="${castor_x} ${castor_y} ${castor_z}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="castor"/>
    </joint>

    <!-- Castor Link  -->

    <link name="castor">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${castor_radius}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${castor_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${castor_mass}" radius="${castor_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

</robot>